### ISSUE TITLE
Package no longer works as version 1.21 has been removed from signal's server

### ISSUE THREAD

**Issue by rbrooklyn** [KaOS-Community-Packages/signal-desktop#1]
I have attached a fixed PKGBUILD file for 1.22.0, which I've had to rename with a .TXT suffix for it to attach here.

The changes are very minimal.
[PKGBUILD.TXT](https://github.com/KaOS-Community-Packages/signal-desktop/files/2949932/PKGBUILD.TXT)

**Comment by verbumfeit** [comment]
Looks good to me :)

FYI you don't have to create issues if you now the solution in the community repos (and it works), just commit your changes directly to master
